# Generated by Django 6.0.5 on 2026-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(default='UNKNOWN', max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fine_amount', models.IntegerField(default=500)),
                ('image_evidence', models.ImageField(blank=True, null=True, upload_to='violations/')),
            ],
        ),
    ]
